### PR TITLE
Feature/upload

### PR DESCRIPTION
**Pull request by StaudenmannM**
Allow to create a nomenclature and upload multiple cards. DB Structure changed to deal with object complexity (see Data model).

### CODE REVIEW

**Comment by bobman38** [comment]
Hello

I can't load fixtures with this branch (`bin/console doctrine:fixtures:load`) because of the `setLabel` method used on `Image`. Maybe to be reworked ?

I will create an issue to run fixtures during the CI process.

**Comment by bobman38** [comment]
Hello Bis

I can't see the index page: 

> Neither the property "label" nor one of the methods "label()", "getlabel()"/"islabel()"/"haslabel()" or "__call()" exist and have public access in class "App\Entity\Image".

Because of the `{{image.label}}` in `index.html.twig`

**Comment by StaudenmannM** [comment]
My fault. I was supposed to keep the label but set it a nullable but directly published the final code :page_facing_up: I updated the fixture and homepage code to display nomenclature content.

**Comment by bobman38** [comment]
I have pushed a fix for easy_admin to handle Card, Nomenclature.

I am thinking of something to simplify the data model : can we put directly the image file inside the Card entity ? If the relation between Card and Image is always 1-1 ?

**Comment by StaudenmannM** [comment]
An image can be used by several cards (same image but different nomenclature context) so I think it make sense to keep it outside.

**Comment by bobman38** [comment]
OK got it :) So let's merge :)

**Pull request merged**
