### PR TITLE
Social Auth

### PR DESCRIPTION
**Pull request by bobman38**
Here is finally a proposition to implement Social Auth. It is using a classic bundle for that (https://github.com/hwi/HWIOAuthBundle) and I have decided to implement the following 2 systems:
- Facebook 
- Google

More is for sure possible. But I think it is a good start.

To test it locally it is mandatory to setup the environment var `FB_ID` `FB_SECRET` `GOOGLE_ID` `GOOGLE_SECRET` that you can get when you create a facebook app with Facebook Login, and a Google Application.

I have deployed the branch on Heroku [here](https://montessori-ressources.herokuapp.com) and the google/FB auth is working good.

### CODE REVIEW

**Comment by StaudenmannM** [comment]
I tried to login with Facebook but got the error "Identifiant d’application invalide"... is there any secreet key not in the repo somewhere ?

**Comment by bobman38** [comment]
Hello

Yep the repo is not containing any id/secret for fb and google auth. If you want to test I can send you mine or you can generate some on your side... I send you that ok ?

**Comment by StaudenmannM** [comment]
Ok send them in a separate email (not linked to github) when you have time :)

Le 7 mai 2019 23:37:12 GMT+08:00, Julien Bras <notifications@github.com> a écrit :
>Hello
>
>Yep the repo is not containing any id/secret for fb and google auth. If
>you want to test I can send you mine or you can generate some on your
>side... I send you that ok ?
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/montessori-ressources/web/pull/18#issuecomment-490132767

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bobman38** [comment]
Done !

**Pull request merged**
