### PR TITLE
first try with dropzonejs integration for adding nomenclature

### PR DESCRIPTION
**Pull request by bobman38**
Hello

Trying the [dropzonejs](https://www.dropzonejs.com) integration that provide us a dropzone location to create a nomenclature in seconds instead of actual way to create nomenclature. It take me only a couple of hours (3 ? ) to setup this so very few code done by myself.

Here is a short gif to show the feature:

- The user drop the image on the dropzone
- It trigger the upload (one by one to avoid limitations)
- after the upload I grab the images id created
- I send that to a back controller that will assemblate that in a new nomenclature
- if success then it go to the edit nomenclature page.

Maybe this can fix this old #27 issue ?

Let me know, I am open to suggestion !

### CODE REVIEW

**Comment by bobman38** [comment]
Allo @analuspi, just quick question do you have tested the pull request or just read it ? 😄 

I think a good process for not obvious evolution (this one is not obvious, not just text change) can be: 
- read the pull request content
- do comments remarks on code if needed
- test the code on local computer (checkout the PR branch and run the code)
- validate if no 'blocking' comment and code woking as expected on local

Thanks !

**Comment by analuspi** [comment]
Ah, ok, thanks!

So I should do a `git pull` from this specific branch in my terminal?

**Comment by bobman38** [comment]
yes kind of ;)

make sure that your work copy is clean (nothing to commit etc...)

run `git checkout feature/dropzone`

test the thing

the go back to your branch `git checkout feature/tags`

**Comment by bobman38** [comment]
Let's merge that !

**Pull request merged**
